### ISSUE TITLE
need to add custom web searches as default in Chrome

### ISSUE THREAD

**Issue by pacharanero** [open-health-hub/nhsbuntu#1]
* BNF
* MedicinesComplete search
* UpToDate (although this starts to look like commercial sponsorship and some open sourcerers might not like it)
* NHSchoices
* GPnotebook (commercial as well)

**Comment by robdyke** [comment]
Bookmarks and search engine preferences are set [here](https://github.com/NHSbuntu/nhsbuntu-default-settings/blob/master/webbrowser)
