### ISSUE TITLE
nhsbuntu should ship with Firefox ESR (Extended Support Release)

### ISSUE THREAD

**Issue by pacharanero** [open-health-hub/nhsbuntu#18]
As a person in charge of managing a large number of NHSbuntu deployments
I need a relatively stable, long term supported browser platform 
So that I can reduce the need for redeployments and updates to browser-dependent software

**Comment by robdyke** [comment]
[Firefox ESR](https://www.mozilla.org/en-US/firefox/organizations/) is intended for groups who deploy and maintain the desktop environment in large organizations such as universities and other schools, county or city governments and businesses

**Comment by robdyke** [comment]
Specifying Firefox ESR is a localisation. Use localisation packages to specify this for your deployment.
