### ISSUE TITLE
How can we use the NHS attacks to really show people that it's a problem?

### ISSUE THREAD

**Issue by crabcrabcam** [open-health-hub/nhsbuntu#34]
I'm not 100% caught up on this story.

Obviously it would have happened on any version of Windows because it's ransomware but right now they seem to be waiting on Microsoft to update the security on the system which obviously MS doesn't have to do as XP was EOL'd 3 years ago. I think obviously wait until it's all fixed before going in, really no point in taking up anyone's time before it's fixed but afterwards it might be a good idea to start trying to get talks directly with people that can get this going. How far is it towards having the main parts in? I tried it in a VM a little but I didn't try any of the specific software just the Office implementation (LibreOffice is obviously fine but the MSOffice logos could be a problem) 

Might also be worth setting up a sub-reddit or something for people to discuss more general things and leave the bugs to here? 

Great work though and I'll try and help out where I can :)

**Comment by pacharanero** [comment]
Thanks for commenting and glad to have your support. It's a community project!

We have a forum:
https://www.openhealthhub.org/c/nhsbuntu

And we also have a Slack channel, which I can add you to if you like - we do need something that's more 'open' than Slack though!

**Comment by pacharanero** [comment]
Gonna close this issue now, but see you on the forum I hope.
