### ISSUE TITLE
Default wallpaper not suitable for 17" display

### ISSUE THREAD

**Issue by Mraanderson** [open-health-hub/nhsbuntu#35]
Cuts off some of the credit text. As the more replaceable computers may have a 17" screen these are also more likely to be converted to NHSbuntu.

Can the background image be adjusted to allow for various screen resolutions please?

**Comment by robdyke** [comment]
Yes. 
This request relates to nhsbuntu-default-settings and may be fixed in https://github.com/NHSbuntu/nhsbuntu-default-settings/commit/f759321ab169bbda6e51c861eb67e359f99389bb

**Comment by Mraanderson** [comment]
Can I make a suggestion, based on previous experience? Making the wallpaper graphic very small and centred and then having the background colour hex matched to the graphic works on all screens. This also reduces the image file size.

**Comment by pacharanero** [comment]
Nice suggestion.

We should also include some kind of easily editable template to enable
trusts to customise the desktop, maybe? A lot of them seem to have a custom
desktop wallpaper, with various trust information on it, we should
facilitate this if it eases adoption...

M

**Comment by robdyke** [comment]
Fixed in https://github.com/NHSbuntu/nhsbuntu-default-settings/pull/7
