### ISSUE TITLE
Remove unnecessary packages on final ISO

### ISSUE THREAD

**Issue by Mraanderson** [open-health-hub/nhsbuntu#39]
As the distribution is aimed at a work environment maybe the installed packages should reflect that. Stripping out games and technical packages would be a start. Documenting the removed items from the default 16.04 would help the IT teams see what has been removed.

**Comment by robdyke** [comment]
Thanks for your input. I'll generate a list of packages and groups installed for review by the community.

**Comment by robdyke** [comment]
Here's a commit that removes Games etc.

https://github.com/NHSbuntu/nhsbuntu-default-settings/commit/7b5e46742eeccf54da4b9b095fd0064ac3e41d95
