### ISSUE TITLE
Add relevant packages to the final ISO

### ISSUE THREAD

**Issue by Mraanderson** [open-health-hub/nhsbuntu#40]
Additional packages suited to the clinical nature of the installation location may be useful. RDP client for fallback, any clinical calculation apps or links to websites, good NHS guidelines links etc

**Comment by robdyke** [comment]
Remmina RDP included with this commit. 

https://github.com/NHSbuntu/nhsbuntu-default-settings/commit/7b5e46742eeccf54da4b9b095fd0064ac3e41d95

**Comment by robdyke** [comment]
Firefox bookmarks are set [here](https://github.com/NHSbuntu/nhsbuntu-default-settings/tree/master/webbrowser).
