### ISSUE TITLE
Windows 10 icons could cause issues in regard to copyright

### ISSUE THREAD

**Issue by SharpOB** [open-health-hub/nhsbuntu#42]
Using Windows 10's icons could very well cause issues with copyright if this OS were to be deployed large scale. Perhaps use a different icon theme? Maybe a different DE altogether? I don't think Gnome 3 would be a good fit for XP-hardware machines. Consider XFCE or LXDE.

Also, have you considered using WPS Office as an alternative to LibreOffice? It has a UI that people would be more familiar and works 100% with Microsoft Office created documents unlike LibreOffice.

**Comment by jimhaddon** [comment]
Agree with the icons, disagree with WPS Office. It's not open source which is the main point of this project.

**Comment by mikemoate** [comment]
Microsoft icon usage is definitely a problem, see https://www.microsoft.com/en-us/legal/intellectualproperty/permissions (under Microsoft Icons).

Also a cautionary reminder, that just because it's on GitHub (https://github.com/B00merang-Project/Windows-10-Icons) doesn't mean it is legal!

**Comment by pacharanero** [comment]
added to project for desktop improvements

**Comment by dominichayesferen** [comment]
@pacharanero If you really need it, you can temporarily borrow the script off of the Windows 10 Theme Installer from my feren OS if you want to, which would mean that you can add it to the startup somehow, and then make it download and install the Windows 10 Icon Set straight from Elbullazul's Repo, meaning, if anything, you'll have a little protection in that the Icons don't come with the ISO that YOU upload.
[postinst.txt](https://github.com/NHSbuntu/nhsbuntu/files/1345115/postinst.txt)
^ It's a Bash Script, but GitHub made me upload it as a TXT file.

**Comment by robdyke** [comment]
These have been removed from NHSbuntu and NHoS.
