### ISSUE TITLE
Maximise / Restore / Minimise buttons are missing by default

### ISSUE THREAD

**Issue by jimhaddon** [open-health-hub/nhsbuntu#43]
The theme used in Gnome appears to not show the above buttons by default. This will be confusing for new users coming from Windows.

**Comment by pacharanero** [comment]
We anticipate that this issue will go away once we move to Cinnamon, which has minimise/maximise/close buttons on the upper right of windows by default.

**Comment by robdyke** [comment]
Resolved in NHoS.
