### ISSUE TITLE
NHSbuntu should use Cinnamon desktop 

### ISSUE THREAD

**Issue by pacharanero** [open-health-hub/nhsbuntu#45]
In an effort to smooth the transition for Windows users, I propose using the Cinnamon desktop, which is much more familiar territory for Windows 7/10 users:

* Taskbar is a 'traditional' style and is at the bottom as in Windows
* System tray is on the bottom right as in Windows
* 'Start' / kicker menu is bottom left as in Windows
* Minimise/Maximise/Close window decorations are on the right of the title bar
* Double-click on a file (in the Nemo file manager) with a short gap between clicks, alows renaming of the item as in Windows

Additionally, Cinnamon is arguably less resource-hungry than Gnome3, which has all kinds of transparency and animation effects going on all over the place.

**Comment by pacharanero** [comment]
Although Cinnamon can simply be added via PPA (`sudo add-apt-repository embrosyn/cinnamon`) this misses out a lot of what makes the Mint desktop visually appealing such as icon themes, window decoration, and desktop themes.

Therefore I suggest using the Mint repos for this: (the below taken from /etc/apt/sources.d/official-package-repositories.list on my Mint 18.2 system)

`deb http://packages.linuxmint.com sonya main upstream import backport`

We also need eventually to remove all Gnome3-related foo such as the Gnome 3 DE, Nautilus, etc

**Comment by pacharanero** [comment]
Thinking about this, it seems madness not to just use Mint 18.2 as our distro base???

**Comment by Mraanderson** [comment]
I was reading down through and reached the same conclusion as your last comment. Mint is an excellent transition distribution. Cinnamon or Mate would definitely be less of a shock than Gnome.
