### ISSUE TITLE
Launchers for NHSbuntu - a look at the options available

### ISSUE THREAD

**Issue by pacharanero** [open-health-hub/nhsbuntu#47]
Users of Ubuntu who like Unity Dash, as well as MacOS users who like launcher platforms such as Alfred and even just the Spotlight search, will like having a good application launcher in NHSBuntu. Windows users will not necessarily have seen such a thing before but may like the idea of being able to do tasks rapidly following a key combination.

For those who don't use a launcher, a launcher is a text box which pops up when you use a particular key combination (often Ctrl + Space, Alt + Space, anything that is very quick and easy to execute). You can then type into the text box to launch applications, find files, play music, execute shell commands, search the web, and many other activities. 

# Synapse
* https://launchpad.net/synapse-project
* Language: Vala
* For a long time this is what I used for my own system, I briefly changed to Zazu when I heard about it, but I have to admit I've changed back to Synapse recently due to Zazu's very slow performance
* **Pros**: very fast, no noticeable lag, searches through your 'last used documents' to rapidly suggest things 
* **Cons**: written in Vala (Wat?), documentation is poor, not particularly responsive to feature requests, project managed on Bazaar & Launchpad (as opposed to GitHub)

# Zazu
* http://zazuapp.org/
![image](https://user-images.githubusercontent.com/2348385/28079979-43a54a84-6662-11e7-96d1-50707fa9dae7.png)
* **Language**: JS/HTML/CSS + Electron
* Zazu is a relatively new entrant, and is cross-platform, available for MacOS, Windows, and Linux.
* It's based on the Electron cross-platform native application framework and is written in Javascript/HTML/CSS
* **Pros**:
* **Cons**:
* **Suitability for NHSbuntu**:

# Albert
* https://albertlauncher.github.io/
![image](https://user-images.githubusercontent.com/2348385/28080086-9a66967a-6662-11e7-8148-8a9d2aaae842.png)
* **Language**: C++, Qt5
* **Pros**: Fast performance, extensions can be written in 
* **Cons**:
* **Suitability for NHSbuntu**: Moderate

# Ulauncher http://ulauncher.io/
![image](https://user-images.githubusercontent.com/2348385/28080014-63398432-6662-11e7-9f5b-cea275b2f4a1.png)
* **Language**: Python
* **Pros**:
* **Cons**:
* **Suitability for NHSbuntu**: Moderate

------

# Unity Dash
![image](https://user-images.githubusercontent.com/2348385/28079833-be0fd772-6661-11e7-9cf0-fddf99b5fe85.png)
* **Language**: Vala, C, C++
* **Pros**: 
* **Cons**: Pretty much tied to Unity as a desktop environment, not standalone
* **Suitability for NHSbuntu**: None

# Kupfer
* https://kupferlauncher.github.io/
* **Language**: Python
* **Pros**:
* **Cons**:
* **Suitability for NHSbuntu**: None

# Gnome Do
* http://do.cooperteam.net/
![image](https://user-images.githubusercontent.com/2348385/28080326-843d66a2-6663-11e7-9c15-1614636b723b.png)
* **Language**: C# (?)
* **Pros**: -
* **Cons**: It's a dead project, no recent updates on Launchpad https://launchpad.net/~do-core/+archive/ubuntu/ppa
* **Suitability for NHSbuntu**: None

**Comment by technotariat** [comment]
Personally a fan of Dmenu http://tools.suckless.org/dmenu/. Came pre-installed as part of Crunchbang shows up as a little toolbar at bottom of the screen.

Screenshot here (dmenu at top of screen) http://www.adercon.com/ac/sites/default/files/dmenu.png

**Comment by pacharanero** [comment]
Can you get me a screenshot?
The link you gave just has a fairly bald 'here have some code' download link

M

**Comment by pacharanero** [comment]
I've migrated this issue (which was never really an issue, it's more like a blog) to Medium, where it makes a lot more sense https://medium.com/nhsbuntu
